project_name: wasker-directory

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

snapshot:
  name_template: 'SNAPSHOT-{{ .Commit }}'

report_sizes: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/kirychukyurii/wdeploy-directory/cmd.version={{ .Version }}
      - -X github.com/kirychukyurii/wdeploy-directory/cmd.commit={{ .Commit }}
      - -X github.com/kirychukyurii/wdeploy-directory/cmd.commitDate={{ .CommitDate }}

universal_binaries:
  - replace: false

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Security updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: 'Build process updates'
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds_info:
      group: root
      owner: root
    rlcp: true
    files:
      - README.md

milestones:
  - close: true

release:
  footer: |
    **Full Changelog**: https://github.com/kirychukyurii/wdeploy-directory/compare/{{ .PreviousTag }}...{{ .Tag }}